[package]
name = "mela"
version = "0.1.0"
authors = ["Aatu Hieta <aatu@hieta.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gltf = { version = "0.15.2", features = ["import", "extras", "KHR_lights_punctual"]}
env_logger = "0.7.1"
image = "0.23"
futures = "0.3"
#imgui = "0.3.0"
nalgebra = "0.21.1"
ncollide2d = "0.22.0"
ncollide3d = "0.23.2"
nphysics3d = "0.16.1"
openxr = { version = "0.12.1", features = ["loaded"] }
rand = "0.7.3"
replace_with = "0.1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-xml-rs = "0.4"
winit = "0.22.0"
wgpu = "0.5"
zerocopy = "0.2"

[profile.release]
debug = true

[[example]]
name="hello3d"
path="examples/hello3d/main.rs"
test=true

[[example]]
name="hello2d"
path="examples/hello2d/main.rs"
test=true

[[example]]
name="ld46"
path="examples/ld46/main.rs"
test=true

#[[example]]
#name="vr"
#path="examples/vr/main.rs"